package currencyConverter;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author adolf
 */
public class currencyConverter extends javax.swing.JFrame {

    String[] unitsConvertion = {"Choose one...", "Mexican Peso", "USA Dollar", "Euro", "Sterling Pound", "Japanise Yen","South-Korea Won"};

    
    /**
     * Creates new form currencyConverter
     */
    public currencyConverter() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public Image getIconImage (){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/alura_icon_IV.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCurrencyToExchange = new javax.swing.JTextField();
        jComboBoxToUnitCurrency = new javax.swing.JComboBox<>();
        jLabelCurrencyConvertion = new javax.swing.JLabel();
        jLabelHelpCurrencyConvertion = new javax.swing.JLabel();
        jButtonPrevWindow = new javax.swing.JButton();
        jButtonRunCurrencyConverter = new javax.swing.JButton();
        jComboBoxFromUnitCurrency = new javax.swing.JComboBox<>();
        jLabelFromUnitCurrency = new javax.swing.JLabel();
        jTextFieldCurrencyExchanged = new javax.swing.JTextField();
        jLabelToUnitCurrency = new javax.swing.JLabel();
        jLabelUnitCurrencyExchanged = new javax.swing.JLabel();
        jLabelUnitCurrencyEntered = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTextFieldCurrencyToExchange.setText("Enter Value");
        jTextFieldCurrencyToExchange.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCurrencyToExchangeFocusGained(evt);
            }
        });

        jComboBoxToUnitCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Mexican Peso", "USA Dollar", "Euro", "Sterling Pound", "Japanise Yen", "South-Korea Won " }));
        jComboBoxToUnitCurrency.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxToUnitCurrencyItemStateChanged(evt);
            }
        });

        jLabelCurrencyConvertion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelCurrencyConvertion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrencyConvertion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrencyConvertion.setText("Currency convertion");
        jLabelCurrencyConvertion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHelpCurrencyConvertion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHelpCurrencyConvertion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_help_outline_white_36.png"))); // NOI18N
        jLabelHelpCurrencyConvertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHelpCurrencyConvertionMouseClicked(evt);
            }
        });

        jButtonPrevWindow.setText("Prev");
        jButtonPrevWindow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrevWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevWindowActionPerformed(evt);
            }
        });

        jButtonRunCurrencyConverter.setText("Run");
        jButtonRunCurrencyConverter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRunCurrencyConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCurrencyConverterActionPerformed(evt);
            }
        });

        jComboBoxFromUnitCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Mexican Peso", "USA Dollar", "Euro", "Sterling Pound", "Japanise Yen", "South-Korea Won " }));
        jComboBoxFromUnitCurrency.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFromUnitCurrencyItemStateChanged(evt);
            }
        });

        jLabelFromUnitCurrency.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelFromUnitCurrency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFromUnitCurrency.setText("From Currency Of");

        jTextFieldCurrencyExchanged.setEditable(false);
        jTextFieldCurrencyExchanged.setText("Enter Value");

        jLabelToUnitCurrency.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelToUnitCurrency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToUnitCurrency.setText("To Currency Of");

        jLabelUnitCurrencyExchanged.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelUnitCurrencyExchanged.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUnitCurrencyExchanged.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnitCurrencyExchanged.setText("Unit");

        jLabelUnitCurrencyEntered.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelUnitCurrencyEntered.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUnitCurrencyEntered.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnitCurrencyEntered.setText("Unit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFromUnitCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFromUnitCurrency)
                    .addComponent(jTextFieldCurrencyToExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnitCurrencyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxToUnitCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelToUnitCurrency))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUnitCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCurrencyConvertion)
                .addGap(120, 120, 120)
                .addComponent(jLabelHelpCurrencyConvertion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jButtonRunCurrencyConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrevWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHelpCurrencyConvertion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelCurrencyConvertion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFromUnitCurrency)
                    .addComponent(jLabelToUnitCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFromUnitCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxToUnitCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCurrencyToExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnitCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnitCurrencyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRunCurrencyConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrevWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevWindowActionPerformed

        this.toBack();
        setVisible(false);
        new SelectProgram().toFront();
        new SelectProgram().setState(java.awt.Frame.NORMAL);

    }//GEN-LAST:event_jButtonPrevWindowActionPerformed

    private void jButtonRunCurrencyConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCurrencyConverterActionPerformed

        String actualCurrency;
        actualCurrency = jComboBoxFromUnitCurrency.getSelectedItem().toString();

        String convertionUnitCurrency;
        convertionUnitCurrency = jComboBoxToUnitCurrency.getSelectedItem().toString();
        
        if(jComboBoxFromUnitCurrency.getSelectedIndex()==0){           
            JOptionPane.showMessageDialog(null, "Select the type of currency entered", "Select the currency",JOptionPane.INFORMATION_MESSAGE);           
        }
        if(jComboBoxToUnitCurrency.getSelectedIndex() == 0){           
            JOptionPane.showMessageDialog(null, "Select the desired type currency to be exchanged", "Select the currency",JOptionPane.INFORMATION_MESSAGE);           
        }
        if(jTextFieldCurrencyToExchange.getText().equals("Enter Value")||jTextFieldCurrencyToExchange.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Type a currency value to be exchanged", "Type  value to exchange",JOptionPane.INFORMATION_MESSAGE);
        }

        /*
        if (actualCurrency.equals("Currency Convertion")) {
            this.toBack();
            currencyConverter cc = new currencyConverter();
            cc.setVisible(true);
            cc.toFront();
        } else if (programSelected.equals("Temperature Convertion")) {
            this.toBack();
            temperatureConverter tc = new temperatureConverter();
            tc.setVisible(true);
            tc.toFront();
        } else {
            JOptionPane.showMessageDialog(this, "Select a convertion program to run", "Make a selection", JOptionPane.ERROR_MESSAGE);
        }
         */
    }//GEN-LAST:event_jButtonRunCurrencyConverterActionPerformed

    private void jLabelHelpCurrencyConvertionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHelpCurrencyConvertionMouseClicked
        JOptionPane.showMessageDialog(this,
                "Instruccions of usage \n"
                + "1-.Select the unit of currency entered \n"
                + "2-.Enter a value to be converted \n"
                + "3-.Select a currency unit to be converted", "Help on usage", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelHelpCurrencyConvertionMouseClicked

    private void jComboBoxFromUnitCurrencyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFromUnitCurrencyItemStateChanged
        int position = jComboBoxFromUnitCurrency.getSelectedIndex();
        jLabelUnitCurrencyEntered.setText(unitsConvertion[position]);
    }//GEN-LAST:event_jComboBoxFromUnitCurrencyItemStateChanged

    private void jComboBoxToUnitCurrencyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxToUnitCurrencyItemStateChanged
         int position = jComboBoxToUnitCurrency.getSelectedIndex();
        jLabelUnitCurrencyExchanged.setText(unitsConvertion[position]);
    }//GEN-LAST:event_jComboBoxToUnitCurrencyItemStateChanged

    private void jTextFieldCurrencyToExchangeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCurrencyToExchangeFocusGained
        jTextFieldCurrencyToExchange.setText("");
    }//GEN-LAST:event_jTextFieldCurrencyToExchangeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrevWindow;
    private javax.swing.JButton jButtonRunCurrencyConverter;
    private javax.swing.JComboBox<String> jComboBoxFromUnitCurrency;
    private javax.swing.JComboBox<String> jComboBoxToUnitCurrency;
    private javax.swing.JLabel jLabelCurrencyConvertion;
    private javax.swing.JLabel jLabelFromUnitCurrency;
    private javax.swing.JLabel jLabelHelpCurrencyConvertion;
    private javax.swing.JLabel jLabelToUnitCurrency;
    private javax.swing.JLabel jLabelUnitCurrencyEntered;
    private javax.swing.JLabel jLabelUnitCurrencyExchanged;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCurrencyExchanged;
    private javax.swing.JTextField jTextFieldCurrencyToExchange;
    // End of variables declaration//GEN-END:variables
}
