package currencyConverter;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author adolf
 */
public class CurrencyConverter extends javax.swing.JFrame {

    String[] unitsConvertion = {"Choose one...", "USA Dollar", "Euro", "Sterling Pound", "Japanise Yen", "South-Korea Won"};

    /**
     * Creates new form currencyConverter
     */
    public CurrencyConverter() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/alura_icon_IV.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldAmountCurrencyToExchange = new javax.swing.JTextField();
        jComboBoxExchangeToUnitCurrency = new javax.swing.JComboBox<>();
        jLabelCurrencyConvertion = new javax.swing.JLabel();
        jLabelHelpCurrencyConvertion = new javax.swing.JLabel();
        jButtonPrevWindow = new javax.swing.JButton();
        jButtonRunCurrencyConverter = new javax.swing.JButton();
        jLabelFromUnitCurrency = new javax.swing.JLabel();
        jTextFieldAmountCurrencyExchanged = new javax.swing.JTextField();
        jLabelToUnitCurrency = new javax.swing.JLabel();
        jLabelUnitCurrencyExchanged = new javax.swing.JLabel();
        jLabelUnitCurrencyEntered = new javax.swing.JLabel();
        jTextFieldExchangeFromCurrencyTo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTextFieldAmountCurrencyToExchange.setText("Enter Value");
        jTextFieldAmountCurrencyToExchange.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAmountCurrencyToExchangeFocusGained(evt);
            }
        });

        jComboBoxExchangeToUnitCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "USA Dollar", "Euro", "Sterling Pound", "Japanise Yen", "South-Korean Won" }));
        jComboBoxExchangeToUnitCurrency.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxExchangeToUnitCurrencyItemStateChanged(evt);
            }
        });

        jLabelCurrencyConvertion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelCurrencyConvertion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrencyConvertion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrencyConvertion.setText("Currency convertion");
        jLabelCurrencyConvertion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHelpCurrencyConvertion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHelpCurrencyConvertion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_help_outline_white_36.png"))); // NOI18N
        jLabelHelpCurrencyConvertion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHelpCurrencyConvertionMouseClicked(evt);
            }
        });

        jButtonPrevWindow.setText("Prev");
        jButtonPrevWindow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrevWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevWindowActionPerformed(evt);
            }
        });

        jButtonRunCurrencyConverter.setText("Run");
        jButtonRunCurrencyConverter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRunCurrencyConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCurrencyConverterActionPerformed(evt);
            }
        });

        jLabelFromUnitCurrency.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelFromUnitCurrency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFromUnitCurrency.setText("From Currency Of");

        jTextFieldAmountCurrencyExchanged.setEditable(false);

        jLabelToUnitCurrency.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelToUnitCurrency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToUnitCurrency.setText("To Currency Of");

        jLabelUnitCurrencyExchanged.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelUnitCurrencyExchanged.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUnitCurrencyExchanged.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnitCurrencyExchanged.setText("Unit");

        jLabelUnitCurrencyEntered.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabelUnitCurrencyEntered.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUnitCurrencyEntered.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUnitCurrencyEntered.setText("Unit");

        jTextFieldExchangeFromCurrencyTo.setEditable(false);
        jTextFieldExchangeFromCurrencyTo.setText("Mexican Peso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFromUnitCurrency)
                    .addComponent(jTextFieldAmountCurrencyToExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnitCurrencyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExchangeFromCurrencyTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAmountCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUnitCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelToUnitCurrency)
                            .addComponent(jComboBoxExchangeToUnitCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCurrencyConvertion)
                .addGap(120, 120, 120)
                .addComponent(jLabelHelpCurrencyConvertion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jButtonRunCurrencyConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrevWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHelpCurrencyConvertion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelCurrencyConvertion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFromUnitCurrency)
                    .addComponent(jLabelToUnitCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxExchangeToUnitCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExchangeFromCurrencyTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAmountCurrencyToExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAmountCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnitCurrencyExchanged, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnitCurrencyEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRunCurrencyConverter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrevWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevWindowActionPerformed

        this.toBack();
        setVisible(false);
        new SelectProgram().toFront();
        new SelectProgram().setState(java.awt.Frame.NORMAL);

    }//GEN-LAST:event_jButtonPrevWindowActionPerformed

    private void jButtonRunCurrencyConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCurrencyConverterActionPerformed

        String convertionUnitCurrency;
        convertionUnitCurrency = jComboBoxExchangeToUnitCurrency.getSelectedItem().toString();
        String amountToExchange = jTextFieldAmountCurrencyToExchange.getText();
        String amountExchanged = "";

        if (jComboBoxExchangeToUnitCurrency.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select the desired type currency to be exchanged", "Select the exchange currency", JOptionPane.INFORMATION_MESSAGE);
        }
        if (jTextFieldAmountCurrencyToExchange.getText().equals("Enter Value") || jTextFieldAmountCurrencyToExchange.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Type a currency value to be exchanged", "Type an amount to exchange", JOptionPane.INFORMATION_MESSAGE);
        }

        for (int i = 0; i < amountToExchange.length(); i++) {
            if (!Character.isDigit(amountToExchange.charAt(i))) {
                JOptionPane.showMessageDialog(null, "Please type just numbers", "Not a valid amount", JOptionPane.ERROR_MESSAGE);
                break;
            }
        }

        try {
            switch (convertionUnitCurrency) {
                case "Euro":
                    amountExchanged = Double.toString(0.0475727 * Double.parseDouble(amountToExchange));
                    break;
                case "Sterling Pound":
                    amountExchanged = Double.toString(0.040412689 * Double.parseDouble(amountToExchange));
                    break;
                case "USA Dollar":
                    amountExchanged = Double.toString(0.051148033 * Double.parseDouble(amountToExchange));
                    break;
                case "Japanise Yen":
                    System.out.println(convertionUnitCurrency);
                    amountExchanged = Double.toString(6.490957 * Double.parseDouble(amountToExchange));
                    break;
                case "South-Korean Won":
                    System.out.println(convertionUnitCurrency);
                    amountExchanged = Double.toString(63.796529 * Double.parseDouble(amountToExchange));
                    break;
            }

        } catch (NumberFormatException ex) {

            System.out.println("Check your amount entered, it must contain only numbers");

        }

        jTextFieldAmountCurrencyExchanged.setText(amountExchanged);

    }//GEN-LAST:event_jButtonRunCurrencyConverterActionPerformed

    private void jLabelHelpCurrencyConvertionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHelpCurrencyConvertionMouseClicked
        JOptionPane.showMessageDialog(this,
                "Instruccions of usage \n"
                + "1-.Select the unit of currency entered \n"
                + "2-.Enter a value to be converted \n"
                + "3-.Select a currency unit to be converted", "Help on usage", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelHelpCurrencyConvertionMouseClicked

    private void jComboBoxExchangeToUnitCurrencyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxExchangeToUnitCurrencyItemStateChanged
        int position = jComboBoxExchangeToUnitCurrency.getSelectedIndex();
        jLabelUnitCurrencyExchanged.setText(unitsConvertion[position]);
    }//GEN-LAST:event_jComboBoxExchangeToUnitCurrencyItemStateChanged

    private void jTextFieldAmountCurrencyToExchangeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAmountCurrencyToExchangeFocusGained
        jTextFieldAmountCurrencyToExchange.setText("");
    }//GEN-LAST:event_jTextFieldAmountCurrencyToExchangeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrevWindow;
    private javax.swing.JButton jButtonRunCurrencyConverter;
    private javax.swing.JComboBox<String> jComboBoxExchangeToUnitCurrency;
    private javax.swing.JLabel jLabelCurrencyConvertion;
    private javax.swing.JLabel jLabelFromUnitCurrency;
    private javax.swing.JLabel jLabelHelpCurrencyConvertion;
    private javax.swing.JLabel jLabelToUnitCurrency;
    private javax.swing.JLabel jLabelUnitCurrencyEntered;
    private javax.swing.JLabel jLabelUnitCurrencyExchanged;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAmountCurrencyExchanged;
    private javax.swing.JTextField jTextFieldAmountCurrencyToExchange;
    private javax.swing.JTextField jTextFieldExchangeFromCurrencyTo;
    // End of variables declaration//GEN-END:variables
}
